CREATE TABLE Supplies (
	Patient_ID	INT PRIMARY KEY,
  ICD_10_PCS	VARCHAR(10) PRIMARY KEY,
  Item_ID INT PRIMARY KEY,
	FOREIGN KEY (Patient_ID) REFERENCES Treatment(Patient_ID),
  FOREIGN KEY (Item_ID) REFERENCES Supply(Item_ID),
  FOREIGN KEY (Patient_ID) REFERENCES ICD_10_PCS(Test_Procedure)
	);